### ISSUE TITLE
gscrot project including binary in release section won't run

### ISSUE THREAD

**Issue by wowselim** [gscrot/gscrot#1]
I am getting following exception when running the gscrot jar from release section. I have imported all dependencies of gscrot into eclipse where I get the same exception. If you look at lines 14-18 the UPLOADERS list should contain at least one element. Yet you get an exception for accessing index 0 of a size 0 arraylist.

![screenshot](https://cloud.githubusercontent.com/assets/5699586/18992116/d4b71dca-871c-11e6-9ef6-bdb903b4ea6a.png)

**Comment by wille** [comment]
Remove setSelected() on line 17

**Comment by wowselim** [comment]
Ok, that actually fixed it. Thanks.
